# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff39a483e6b817587ce399ca8cc2b720ad4cd34c267703b19a182fcdcd7c268d5b71751e8b4a0864309c8f8b5fd9ca83360fb4302fe9fcc440ac42b4e7a659b

test:
  secret_key_base: c0a7f6d3d68fb0666012e70cc40fbc4ca809483257a02bde56d227ab5327f54a3204be15cf48e052990926cc5ee344c44237b79d5262fadc4d125cb901c6932d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
